/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jack_elftype_NativeUtils */

#ifndef _Included_com_jack_elftype_NativeUtils
#define _Included_com_jack_elftype_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jack_elftype_NativeUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jack_elftype_NativeUtils_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
